CREATE TABLE "GRADE" (
    "GRADE_CODE" NUMBER NOT NULL,
    "GRADE_NAME" VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN "GRADE"."GRADE_CODE" IS '회원 등급 코드';
COMMENT ON COLUMN "GRADE"."GRADE_NAME" IS '회원 등급명';

-- GRADE 테이블 제약조건 추가
ALTER TABLE GRADE
ADD PRIMARY KEY(GRADE_CODE);

DROP TABLE "MEMBER";

-- 회원 테이블
CREATE TABLE "MEMBER" ( 
   "MEMBER_NO"   NUMBER   NOT NULL,
   "MEMBER_ID"   VARCHAR2(30)  NOT NULL,
   "MEMBER_PW"   VARCHAR2(30) NOT NULL,
   "MEMBER_NAME"   VARCHAR2(30) NOT NULL,
   "MEMBER_NICK"   VARCHAR2(30) NOT NULL,
   "MEMBER_EMAIL"   VARCHAR2(50) NOT NULL,
   "MEMBER_TEL"   CHAR(11) NOT NULL,
   "PROFILE_IMG"   VARCHAR2(200),
   "GRADE_CODE"   NUMBER DEFAULT 1 NOT NULL,
   "POINT"   NUMBER DEFAULT 0 NOT NULL,
   "REG_DATE"   DATE DEFAULT SYSDATE NOT NULL,
   "SECESSION_FL"   CHAR(1)   DEFAULT 'N',
   "SECESSION_DT"   DATE 
   
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원 번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 아이디';
COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '회원 이름';
COMMENT ON COLUMN "MEMBER"."MEMBER_NICK" IS '회원 닉네임';
COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원 이메일';
COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '전화번호(- 미포함)';
COMMENT ON COLUMN "MEMBER"."PROFILE_IMG" IS '회원 프로필 이미지';
COMMENT ON COLUMN "MEMBER"."GRADE_CODE" IS '회원 등급 코드';
COMMENT ON COLUMN "MEMBER"."POINT" IS '포인트';
COMMENT ON COLUMN "MEMBER"."REG_DATE" IS '가입일';
COMMENT ON COLUMN "MEMBER"."SECESSION_FL" IS '탈퇴여부(Y:탈퇴, N:미탈퇴)';
COMMENT ON COLUMN "MEMBER"."SECESSION_DT" IS '탈퇴일자';


-- MEMBER 테이블 제약조건 추가
ALTER TABLE MEMBER
ADD PRIMARY KEY(MEMBER_NO); -- 제약 조건명 생략(SYS_XXXXX)

ALTER TABLE MEMBER
ADD CONSTRAINT "FK_GRADE_CODE" -- 제약 조건명 지정
FOREIGN KEY("GRADE_CODE") -- BOARD의 BOARD_CODE 컬럼에 FK 지정
REFERENCES "GRADE"; -- 참조할 테이블

ALTER TABLE MEMBER
ADD CONSTRAINT "CHK_SECESSION_FL"
CHECK ("SECESSION_FL" IN ('N', 'Y'));

-- UPDATE_DT, DELETE_DT  NULL 허용
ALTER TABLE "MEMBER"
MODIFY "PROFILE_IMG" NULL;

ALTER TABLE "MEMBER"
MODIFY "SECESSION_DT" NULL;

-- MEMBER_NO용 시퀀스
CREATE SEQUENCE SEQ_MEMBER_NO;






-- 게시판 테이블
CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
    "MEMBER_NO" NUMBER NOT NULL,
	"BOARD_TITLE"	VARCHAR2(150)		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"READ_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"CREATE_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"UPDATE_DT"	DATE,
    "BOARD_TYPE" CHAR(1) NOT NULL,
	"BOARD_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"DELETE_DT"	DATE );

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글 번호(시퀀스)';
COMMENT ON COLUMN "BOARD"."MEMBER_NO" IS '회원 번호(시퀀스)';
COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글 제목';
COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글 내용';
COMMENT ON COLUMN "BOARD"."READ_COUNT" IS '조회수(시퀀스)';
COMMENT ON COLUMN "BOARD"."CREATE_DT" IS '게시글 작성일';
COMMENT ON COLUMN "BOARD"."UPDATE_DT" IS '마지막 수정일';
COMMENT ON COLUMN "BOARD"."BOARD_TYPE" IS '게시글 구분(자유=1, 인기=2, 운동=3, 정모=4)';
COMMENT ON COLUMN "BOARD"."BOARD_FL" IS '게시글 삭제여부(미삭제N, 삭제Y)';
COMMENT ON COLUMN "BOARD"."DELETE_DT" IS '게시글 삭제일자';



-- BOARD 테이블 제약조건 추가
ALTER TABLE BOARD
ADD PRIMARY KEY(BOARD_NO); -- 제약 조건명 생략(SYS_XXXXX)

ALTER TABLE BOARD
ADD CONSTRAINT "FK_MEMBER_NO" -- 제약 조건명 지정
FOREIGN KEY("MEMBER_NO") -- BOARD의 BOARD_CODE 컬럼에 FK 지정
REFERENCES "MEMBER"; -- 참조할 테이블

ALTER TABLE BOARD
ADD CONSTRAINT "CHK_BOARD_FL"
CHECK ("BOARD_FL" IN ('N', 'Y'));

-- UPDATE_DT, DELETE_DT  NULL 허용
ALTER TABLE "BOARD"
MODIFY "UPDATE_DT" NULL;

ALTER TABLE "BOARD"
MODIFY "DELETE_DT" NULL;

-- BOARD_NO용 시퀀스
CREATE SEQUENCE SEQ_BOARD_NO;

CREATE SEQUENCE SEQ_BOARD_COUNT;


ALTER TABLE MANAGEMENT RENAME COLUMN STANDDARD TO STANDARD;

SELECT STANDARD FROM MANAGEMENT;