/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-06-15 05:30:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bookmark_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/workspace/SemiProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/team4/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1654780125317L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Bookmark</title>\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/member/bookmark.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("    <main>\r\n");
      out.write("        <section class=\"myPage-content\">\r\n");
      out.write("\r\n");
      out.write("            <section class=\"left-side\">\r\n");
      out.write("                <ul class=\"list-group\">\r\n");
      out.write("                    <li><a href=\"info\">내 정보</a></li>\r\n");
      out.write("                    <li><a href=\"myContent\">내 글 관리</a></li>\r\n");
      out.write("                    <li><a href=\"like\">좋아요 관리</a></li>\r\n");
      out.write("                    <li><a href=\"bookmark\">북마크 관리</a></li>\r\n");
      out.write("                    <li><a href=\"secession\">회원 탈퇴</a></li>\r\n");
      out.write("                    <li><a href=\"#\">쪽지</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </section>\r\n");
      out.write("            \r\n");
      out.write("            <section class=\"myPage-main\">\r\n");
      out.write("                <h2 class=\"title\">\r\n");
      out.write("                    <span>북마크 관리</span>\r\n");
      out.write("                </h2>\r\n");
      out.write("        \r\n");
      out.write("                <div class=\"line\">\r\n");
      out.write("        \r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <table name=\"myContent\" class=\"tb\">\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>번호</th>\r\n");
      out.write("                            <th>카테고리</th>\r\n");
      out.write("                            <th>제목</th>\r\n");
      out.write("                            <th>작성자</th>\r\n");
      out.write("                            <th>작성일</th>\r\n");
      out.write("                            <th></th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("            \r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>10</td>\r\n");
      out.write("                            <td>자유게시판</td>\r\n");
      out.write("                            <td>게시글 10입니다.</td>\r\n");
      out.write("                            <td>user9</td>\r\n");
      out.write("                            <td>2022-05-06</td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <input type=\"checkbox\">\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("        \r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>9</td>\r\n");
      out.write("                            <td>자유게시판</td>\r\n");
      out.write("                            <td>게시글 9입니다.</td>\r\n");
      out.write("                            <td>유저팔</td>\r\n");
      out.write("                            <td>2022-05-06</td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <input type=\"checkbox\">\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("        \r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>8</td>\r\n");
      out.write("                            <td>자유게시판</td>\r\n");
      out.write("                            <td>게시글 8입니다.</td>\r\n");
      out.write("                            <td>유저7</td>\r\n");
      out.write("                            <td>2022-05-04</td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <input type=\"checkbox\">\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("        \r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>7</td>\r\n");
      out.write("                            <td>자유게시판</td>\r\n");
      out.write("                            <td>게시글 7입니다.</td>\r\n");
      out.write("                            <td>user6</td>\r\n");
      out.write("                            <td>2022-05-03</td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <input type=\"checkbox\">\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("        \r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>6</td>\r\n");
      out.write("                            <td>자유게시판</td>\r\n");
      out.write("                            <td>게시글 6입니다.</td>\r\n");
      out.write("                            <td>유저오</td>\r\n");
      out.write("                            <td>2022-05-03</td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <input type=\"checkbox\">\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("        \r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>5</td>\r\n");
      out.write("                            <td>운동게시판</td>\r\n");
      out.write("                            <td>게시글 5입니다.</td>\r\n");
      out.write("                            <td>유저4</td>\r\n");
      out.write("                            <td>2022-05-02</td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <input type=\"checkbox\">\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("        \r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>4</td>\r\n");
      out.write("                            <td>운동게시판</td>\r\n");
      out.write("                            <td>게시글 4입니다.</td>\r\n");
      out.write("                            <td>user3</td>\r\n");
      out.write("                            <td>2022-05-02</td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <input type=\"checkbox\">\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("        \r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>3</td>\r\n");
      out.write("                            <td>운동게시판</td>\r\n");
      out.write("                            <td>게시글 3입니다.</td>\r\n");
      out.write("                            <td>유저이</td>\r\n");
      out.write("                            <td>2022-05-02</td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <input type=\"checkbox\">\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("        \r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>2</td>\r\n");
      out.write("                            <td>운동게시판</td>\r\n");
      out.write("                            <td>게시글 2입니다.</td>\r\n");
      out.write("                            <td>유저1</td>\r\n");
      out.write("                            <td>2022-05-01</td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <input type=\"checkbox\">\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("        \r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>1</td>\r\n");
      out.write("                            <td>운동게시판</td>\r\n");
      out.write("                            <td>게시글 1입니다.</td>\r\n");
      out.write("                            <td>user1</td>\r\n");
      out.write("                            <td>2022-05-01</td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <input type=\"checkbox\">\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"btn-area\">\r\n");
      out.write("                    <button type=\"submit\" id=\"deleteBtn\">삭제</button>\r\n");
      out.write("                </div>\r\n");
      out.write("        \r\n");
      out.write("                \r\n");
      out.write("                <div class=\"pagination-area\">\r\n");
      out.write("                    <ul class=\"pagination\">\r\n");
      out.write("                        <li><a href=\"#\">&lt;</a></li>\r\n");
      out.write("                        <li><a class=\"current\">1</a></li>\r\n");
      out.write("                        <li><a href=\"#\">2</a></li>\r\n");
      out.write("                        <li><a href=\"#\">3</a></li>\r\n");
      out.write("                        <li><a href=\"#\">4</a></li>\r\n");
      out.write("                        <li><a href=\"#\">5</a></li>\r\n");
      out.write("                        <li><a href=\"#\">6</a></li>\r\n");
      out.write("                        <li><a href=\"#\">7</a></li>\r\n");
      out.write("                        <li><a href=\"#\">8</a></li>\r\n");
      out.write("                        <li><a href=\"#\">9</a></li>\r\n");
      out.write("                        <li><a href=\"#\">10</a></li>\r\n");
      out.write("                        <li><a href=\"#\">&gt;</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"line\"></div>\r\n");
      out.write("            </section>\r\n");
      out.write("        </section>\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("    <!-- jQuery 라이브러리 추가 -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\" integrity=\"sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- js -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/member/bookmark.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
