/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-06-15 01:36:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signUp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/workspace/SemiProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/team4/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1654780125317L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>SignUp</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/member/signUp.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>  \r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("    <main>\r\n");
      out.write("	    <section class=\"signUp-main\">\r\n");
      out.write("	        <h2 class=\"title\">\r\n");
      out.write("	            <span class=\"pull-left\">회원가입</span>\r\n");
      out.write("	        </h2>\r\n");
      out.write("	\r\n");
      out.write("	        <div class=\"line\"></div>\r\n");
      out.write("			\r\n");
      out.write("	        <form action=\"signUp\" method=\"POST\" onsubmit=\"return signUpValidate()\">\r\n");
      out.write("	            <table name=\"signUp_form\" class=\"tb\">\r\n");
      out.write("	                <tr>\r\n");
      out.write("	                    <th>아이디</th>\r\n");
      out.write("	                    <td>\r\n");
      out.write("	                        <input type=\"text\" name=\"memberId\" id=\"memberId\"  placeholder=\"아이디를 입력해 주세요\" autocomplete=\"off\">\r\n");
      out.write("	                        <button class=\"member_btn\" id=\"idBtn\" type=\"button\">중복확인</button>\r\n");
      out.write("	                        <br><span class=\"signUp-message\" id=\"idMessage\">영어소문자,숫자,특수문자(-,_) 4~10글자 사이로 작성해주세요.</span>\r\n");
      out.write("	                    </td>\r\n");
      out.write("	                </tr>\r\n");
      out.write("	\r\n");
      out.write("	                <tr>\r\n");
      out.write("	                    <th rowspan=\"2\">비밀번호</th>\r\n");
      out.write("	                    <td style=\"border-bottom: none\">\r\n");
      out.write("	                        <input type=\"password\" name=\"memberPw\" id=\"memberPw\" placeholder=\"비밀번호를 입력해 주세요.\" autocomplete=\"off\">\r\n");
      out.write("	                    </td>\r\n");
      out.write("	                </tr>\r\n");
      out.write("	\r\n");
      out.write("	                <tr>\r\n");
      out.write("	                    <td style=\"border-top: none\">\r\n");
      out.write("	                        <input type=\"password\" name=\"memberPw2\" id=\"memberPw2\" placeholder=\"비밀번호를 한번 더 입력해 주세요\" autocomplete=\"off\">\r\n");
      out.write("	                        <br><span class=\"signUp-message\" id=\"pwMessage\">영어,숫자,특수문자(!,@,#,-,_) 6~30글자 사이로 작성해주세요.</span>\r\n");
      out.write("	                    </td>\r\n");
      out.write("	                </tr>\r\n");
      out.write("	\r\n");
      out.write("	                <tr>\r\n");
      out.write("	                    <th>이름</th>\r\n");
      out.write("	                    <td>\r\n");
      out.write("	                        <input type=\"text\" id=\"memberName\" name=\"memberName\" placeholder=\"이름을 입력해 주세요\" autocomplete=\"off\">\r\n");
      out.write("	                    </td>\r\n");
      out.write("	                </tr>\r\n");
      out.write("	\r\n");
      out.write("	                <tr>\r\n");
      out.write("	                    <th>닉네임</th>\r\n");
      out.write("	                    <td>\r\n");
      out.write("	                        <input type=\"text\" name=\"memberNickname\" value=\"\" id=\"memberNickname\" placeholder=\"닉네임(0글자 이하)을 입력해 주세요\">\r\n");
      out.write("	                        <button class=\"member_btn\" id=\"nicknameBtn\" type=\"button\">중복확인</button>\r\n");
      out.write("	                        <br><span class=\"signUp-message\" id=\"nicknameMessage\">영어/숫자/한글 2~10글자 사이로 작성해주세요.</span>\r\n");
      out.write("	                    </td>\r\n");
      out.write("	                </tr>\r\n");
      out.write("	\r\n");
      out.write("	                <tr>\r\n");
      out.write("	                    <th>전화번호</th>\r\n");
      out.write("	                    <td>\r\n");
      out.write("	                        <input type=\"tel\" name=\"memberTel\" value=\"\" id=\"memberTel\" maxlength=\"13\" placeholder=\"번호를 입력해 주세요\">\r\n");
      out.write("	                        <br><span class=\"signUp-message \" id=\"telMessage\">전화번호를 입력해주세요.(-제외)</span>\r\n");
      out.write("	                    </td>\r\n");
      out.write("	                </tr>\r\n");
      out.write("	\r\n");
      out.write("	                <tr>\r\n");
      out.write("	                    <th>이메일</th>\r\n");
      out.write("	                    <td>\r\n");
      out.write("	                        <input type=\"email\" name=\"memberEmail\" id=\"memberEmail\" placeholder=\"이메일을 입력해 주세요\">\r\n");
      out.write("	                        <button class=\"member_btn\" id=\"checkBtn\" type=\"button\">중복확인</button>\r\n");
      out.write("	                        <button class=\"member_btn\" id=\"sendBtn\" type=\"button\">인증번호 받기</button>\r\n");
      out.write("	                        <br><span class=\"signUp-message\" id=\"emailMessage\">메일을 받을 수 있는 이메일을 입력해주세요.</span>\r\n");
      out.write("	                    </td>\r\n");
      out.write("	                </tr>\r\n");
      out.write("	\r\n");
      out.write("	                <tr>\r\n");
      out.write("	                    <th>인증번호</th>\r\n");
      out.write("	                    <td>\r\n");
      out.write("	                        <input type=\"text\" id=\"cNumber\" placeholder=\"인증번호를 입력해 주세요\">\r\n");
      out.write("	                        <button class=\"member_btn\" type=\"button\" id=\"cBtn\">인증하기</button>\r\n");
      out.write("	                        <br><span class=\"signUp-message\" id=\"cMessage\"></span>\r\n");
      out.write("	                    </td>\r\n");
      out.write("	                </tr>\r\n");
      out.write("	                \r\n");
      out.write("	            </table>\r\n");
      out.write("	\r\n");
      out.write("	            <div class=\"terms\">\r\n");
      out.write("	                <textarea name=\"terms\" id=\"terms\" cols=\"10\" rows=\"10\" style=\"resize: none\">약관내용입니다.\r\n");
      out.write("회원가입 시 약관에 동의한 것으로 간주합니다.</textarea>\r\n");
      out.write("	            </div>\r\n");
      out.write("	\r\n");
      out.write("	            <div class=\"confirm\">\r\n");
      out.write("	                <button id=\"cancel\" type=\"button\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">취소</a></button>\r\n");
      out.write("	                <button id=\"signUpConfirm\">회원가입</button>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            \r\n");
      out.write("	\r\n");
      out.write("	        </form>\r\n");
      out.write("	        <div class=\"line\"></div>\r\n");
      out.write("	    </section>\r\n");
      out.write("		\r\n");
      out.write("    </main>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("    <!-- jQuery 라이브러리 추가 -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\" integrity=\"sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- js -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/member/signUp.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
