SELECT * FROM(
	SELECT ROWNUM RNUM, A.* FROM(
		SELECT BOARD_NO, BOARD_NM, BOARD_TITLE, MEMBER_NICKNAME,
			   TO_CHAR(CREATE_DT, 'YYYY-MM-DD') AS CREATE_DT
		FROM BOARD
		JOIN BOARD_TYPE USING(BOARD_CD)
		JOIN MEMBER USING(MEMBER_NO)
        JOIN REPLY USING(MEMBER_NO)
		WHERE BOARD_FL = 'N'
		AND MEMBER_NO = 1
		ORDER BY BOARD_NO DESC
	) A
)
WHERE RNUM BETWEEN 1 AND 10;


-- ***
SELECT * FROM(
	SELECT ROWNUM RNUM, A.* FROM(
        SELECT *
        FROM (
            SELECT BOARD_NO, BOARD_NM, BOARD_TITLE, MEMBER_NICK,
            TO_CHAR(CREATE_DT, 'YYYY-MM-DD') AS CREATE_DT
            FROM BOARD
            JOIN BOARD_TYPE USING(BOARD_CD)
            JOIN MEMBER USING(MEMBER_NO)
            WHERE BOARD_FL = 'N'
            AND MEMBER_NO = ?
            )
        JOIN REPLY USING(BOARD_NO)
        ) A
)
WHERE RNUM BETWEEN ? AND ?;


-- 내가 쓴 댓글 조회
-- 게시글 번호, 카테고리, 게시글제목, 게시글작성자, 게시글작성일 / 댓글작성일순으로 조회


SELECT *
FROM (
    SELECT BOARD_NO, BOARD_NM, BOARD_TITLE, MEMBER_NICK,
       TO_CHAR(CREATE_DT, 'YYYY-MM-DD') AS CREATE_DT
    FROM BOARD
    JOIN BOARD_TYPE USING(BOARD_CD)
    JOIN MEMBER USING(MEMBER_NO)
    WHERE BOARD_FL = 'N'
    )
JOIN REPLY USING(BOARD_NO)
WHERE MEMBER_NO = 2;








SELECT BOARD_NO, BOARD_NM, BOARD_TITLE, MEMBER_NICKNAME,
        TO_CHAR(CREATE_DT, 'YYYY-MM-DD') AS CREATE_DT
FROM BOARD
JOIN BOARD_TYPE USING(BOARD_CD)
JOIN MEMBER USING(MEMBER_NO)
WHERE BOARD_FL = 'N'
AND MEMBER_NO = 1
ORDER BY BOARD_NO DESC;

SELECT BOARD_NO, BOARD_NM, BOARD_TITLE, MEMBER_NICK,
       TO_CHAR(CREATE_DT, 'YYYY-MM-DD') AS CREATE_DT
FROM BOARD
JOIN BOARD_TYPE USING(BOARD_CD)
JOIN MEMBER USING(MEMBER_NO)
WHERE BOARD_FL = 'N'
AND MEMBER_NO = 1
ORDER BY BOARD_NO DESC;

SELECT (
    SELECT BOARD_NO, BOARD_NM, BOARD_TITLE, MEMBER_NICK,
       TO_CHAR(CREATE_DT, 'YYYY-MM-DD') AS CREATE_DT
    FROM BOARD
    JOIN BOARD_TYPE USING(BOARD_CD)
    JOIN MEMBER USING(MEMBER_NO)
    WHERE BOARD_FL = 'N'
    AND MEMBER_NO = 1
)
FROM REPLY
WHERE REPLY_NO DESC;



